# gitlab ci/cd to build docker images
build_image:
  only:
    refs:
      - deployment
  tags:
    - build
    - hims
  script:
    - cd /d "F:\LOCAL DEV\newrepository\algaeh-monorepo"
    - git config --list
    - git pull
    - algaeh-cli build -a
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose -f docker-compose.yml build
    - docker-compose -f docker-compose.yml push
