# gitlab ci/cd to build docker images
before_script:
  - export DOCKER_HOST=tcp://localhost:2375
  - export PATH="/home/algaeh/.nvm/versions/node/v12.11.1/bin/:$PATH"
build_image:
  only:
    - schedules
    refs:
      - development
  tags:
    - build
    - hims
  script:
    - cd /f/LOCAL\ DEV/newrepository/algaeh-monorepo/
    - git pull
    - echo $PATH
    - algaeh-cli build -a

build_docker:
  only:
    - schedules
    refs:
      - development
  tags:
    - build
    - hims
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose -f docker-compose.yml build
    - docker-compose -f docker-compose.yml push
