# gitlab ci/cd to build docker images
build_image:
  only:
    refs:
      - schedules
  tags:
    - build
    - hims
  script:
    - cd /home/algaeh/algaeh-monorepo
    - git pull
    - algaeh-cli build -a
    - algeah-cli start -a

# build_docker:
#   only:
#     refs:
#       - schedules
#   tags:
#     - build
#     - hims
#   script:
#     - cd /home/algaeh/algaeh-monorepo
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#     - docker-compose -f docker-compose.yml build
#     - docker-compose -f docker-compose.yml push

# start_stack:
#   only:
#     refs:
#       - schedules
#   tags:
#     - build
#     - hims
#   script:
#     - cd /home/algaeh/algaeh-monorepo
#     - docker stack deploy --compose-file=docker-compose.deploy.yml algaeh --with-registry-auth
