# gitlab ci/cd to build docker images
build_image:
  only:
    refs:
      - deployment
  tags:
    - build
    - hims
  script:
    - cd "F:\LOCAL DEV\newrepository\algaeh-monorepo"
    - $env:PATH += ";C:\Users\admin\AppData\Roaming\npm\"
    - algaeh-cli build -a
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose -f docker-compose.yml build
    - docker-compose -f docker-compose.yml push
