version: "3"
services:
  app:
    container_name: docker-hims-erp
    restart: always
    build: .
    volumes:
      - ./:/apps
    ports:
      - "3004:3004"
      - "3000:3000"
      - "3006:3006"
