version: "3"
services:
  core:
    container_name: ${CI_REGISTRY}/algaeh/algaeh-monorepo/algaeh-core
    env_file:
      - ./env
    build:
      context: ./algaeh-core
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  billing:
    container_name: ${CI_REGISTRY}/algaeh/algaeh-monorepo/algaeh-billing
    env_file:
      - ./env
    build:
      context: ./Billing
      dockerfile: Dockerfile
    ports:
      - "3014:3014"
