version: "2.1"

services:
  algaeh-reverse:
    image: nginx
    network_mode: host
    ports:
      - 80:80
    volumes:
      - ./config/nginx-dev.conf:/etc/nginx/nginx.conf
  algaeh-cache:
    image: redis:alpine
    network_mode: bridge
    ports:
      - 6379:6379
