import express from "express";
import department from "../controllers/department";
import visitType from "../controllers/visitType";
import visaType from "../controllers/visaType";
import identity from "../controllers/identity";
import patientType from "../controllers/patientType";
import vendor from "../controllers/vendor";
import serviceType from "../controllers/serviceTypes";
import specialityAndCategory from "../controllers/specialityAndCategory";
import shiftAndCounter from "../controllers/shiftAndCounter";
import currency from "../controllers/currency";
import packagesetup from "../controllers/packagesetup";
import bankmaster from "../controllers/bankmaster";
import companyAccount from "../controllers/companyAccount";
import InsuranceCardClass from "../controllers/InsuranceCardClass";
import sfda from "../controllers/sfda";
import branchMaster from "../controllers/branchMaster";
import favouriteOrders from "../controllers/favouriteOrders";
import customer from "../controllers/customer";
import salseSetup from "../controllers/salseSetup";

const router = express();
router.use("/department", department());
router.use("/visitType", visitType());
router.use("/visaType", visaType());
router.use("/identity", identity());
router.use("/patientType", patientType());
router.use("/vendor", vendor());
router.use("/serviceType", serviceType());
router.use("/specialityAndCategory", specialityAndCategory());
router.use("/shiftAndCounter", shiftAndCounter());
router.use("/currency", currency());
router.use("/packagesetup", packagesetup());
router.use("/bankmaster", bankmaster());
router.use("/companyAccount", companyAccount());
router.use("/InsuranceCardClass", InsuranceCardClass());
router.use("/sfda", sfda());
router.use("/branchMaster", branchMaster());
router.use("/favouriteOrders", favouriteOrders());
router.use("/customer", customer());
router.use("/salseSetup", salseSetup());

export default router;
