import express from "express";
import middleware from "../middleware";
// import initializedDb from "../db";
//import config from "../keys/keys";
const con = require("algaeh-keys/keys");
import account from "../controller/account";
import employee from "../controller/employee";
import department from "../controller/department";
import identity from "../controller/identity";
import visitType from "../controller/visitType";
import patientRegisteration from "../controller/patientRegistration";
import frontDesk from "../controller/frontDesk";
import getMasters from "../controller/masters";
import updateMaster from "../controller/updateMasters";
import languageTranslator from "../controller/languageTranslator";
import visit from "../controller/visit";
import serviceType from "../controller/serviceType";
import billing from "../controller/billing";
import patientType from "../controller/patientType";
import globalSearch from "../controller/globalSearch";
import insurance from "../controller/insurance";
import opBilling from "../controller/opBilling";
import userPreferences from "../controller/userPreferences";
import doctorsWorkBench from "../EHR/controller/doctorsWorkBench";
import hpi from "../EHR/controller/hpi";
import orderAndPreApproval from "../controller/orderAndPreApproval";
import laboratory from "../controller/laboratory";
import labmasters from "../controller/labmasters";
import investigation from "../controller/investigation";
import icdcptcodes from "../controller/icdcptcodes";
import radiology from "../controller/radiology";
import algaehappuser from "../controller/algaehappuser";
import dietmaster from "../controller/dietmaster";
import orderMedication from "../controller/orderMedication";
import organization from "../controller/organization";
import pharmacy from "../Pharmacy/controller/pharmacy";
import appointment from "../controller/appointment";
import doctorsCommission from "../controller/doctorsCommission";
import employeesetups from "../controller/employeesetups";
import initialstock from "../Pharmacy/controller/initialstock";
import pharmacyGlobal from "../Pharmacy/controller/pharmacyGlobal";
import posEntry from "../Pharmacy/controller/posEntry";
import mrd from "../controller/mrd";
import requisitionEntry from "../Pharmacy/controller/requisitionEntry";
import salesReturn from "../Pharmacy/controller/salesReturn";
import transferEntry from "../Pharmacy/controller/transferEntry";
import shiftAndCounter from "../controller/shiftAndCounter";
import ucaf from "../controller/ucaf";
import dcaf from "../controller/dcaf";
import ocaf from "../controller/ocaf";
import workBenchSetup from "../EHR/controller/workBenchSetup";
import invoiceGeneration from "../controller/invoiceGeneration";
import currency from "../controller/currency";
import generateReport from "../controller/generateReport";
import inventory from "../Inventory/controller/inventory";
import inventoryinitialstock from "../Inventory/controller/inventoryinitialstock";
import inventoryGlobal from "../Inventory/controller/inventoryGlobal";
import inventoryrequisitionEntry from "../Inventory/controller/inventoryrequisitionEntry";
import inventorytransferEntry from "../Inventory/controller/inventorytransferEntry";
import POSCreditSettlement from "../Pharmacy/controller/POSCreditSettlement";

import specialityAndCategory from "../controller/specialityAndCategory";
import vendor from "../controller/vendor";
import PurchaseOrderEntry from "../Procurement/controller/PurchaseOrderEntry";
import DeliveryNoteEntry from "../Procurement/controller/DeliveryNoteEntry";
import nurseWorkBench from "../EHR/controller/nurseWorkBench";
import ReceiptEntry from "../Procurement/controller/ReceiptEntry";
import opBillCancellation from "../controller/opBillCancellation";
import opCreditSettlement from "../controller/opCreditSettlement";
import algaehMasters from "../controller/algaehMasters";
import dental from "../controller/dental";

import algaehappexpiry from "../controller/algaehappexpiry";
import selfService from "../SelfService/controller/selfService";
let router = express();
import leave from "../Payroll/controller/leave";
import holiday from "../Payroll/controller/holiday";
import loan from "../Payroll/controller/loan";
import salary from "../Payroll/controller/salary";
import payrollSettings from "../Payroll/controller/payrollSettings";
import examinationDiagrams from "../EHR/controller/examinationDiagram";
import dentalForm from "../EHR/controller/dentalForm";
import opthometry from "../EHR/controller/opthometry";

import diagram from "../controller/diagram";
import myInit from "../controller/myinit";

//connect to DB
//function(db)
const config = con.default;
const db={};
//initializedDb(db => {
  //internal middleware
  // router.use(middleware({ config, db }));
  //api router v1
  router.use("/init", myInit());
  router.use("/apiAuth", account({ config, db }));
  router.use("/employee", employee({ config, db }));
  router.use("/department", department({ config, db }));
  router.use("/identity", identity({ config, db }));
  router.use("/visitType", visitType({ config, db }));
  router.use("/patient", patientRegisteration({ config, db }));
  router.use("/frontDesk", frontDesk({ config, db }));
  router.use("/masters/get", getMasters());
  router.use("/masters/set", updateMaster());
  router.use("/masters", getMasters());
  router.use("/translator", languageTranslator());
  router.use("/visit", visit({ config, db }));
  router.use("/serviceType", serviceType({ config, db }));
  router.use("/billing", billing({ config, db }));
  router.use("/patientType", patientType({ config, db }));
  router.use("/insurance", insurance({ config, db }));
  router.use("/gloabelSearch", globalSearch());
  router.use("/opBilling", opBilling({ config, db }));
  router.use("/userPreferences", userPreferences());
  router.use("/doctorsWorkBench", doctorsWorkBench({ config, db }));
  router.use("/hpi", hpi({ config, db }));
  router.use("/orderAndPreApproval", orderAndPreApproval({ config, db }));
  router.use("/laboratory", laboratory({ config, db }));
  router.use("/labmasters", labmasters({ config, db }));
  router.use("/investigation", investigation({ config, db }));
  router.use("/icdcptcodes", icdcptcodes({ config, db }));
  router.use("/radiology", radiology({ config, db }));
  router.use("/algaehappuser", algaehappuser({ config, db }));
  router.use("/dietmaster", dietmaster({ config, db }));

  router.use("/orderMedication", orderMedication({ config, db }));
  router.use("/organization", organization({ config, db }));
  router.use("/pharmacy", pharmacy({ config, db }));
  router.use("/appointment", appointment({ config, db }));
  router.use("/doctorsCommission", doctorsCommission({ config, db }));
  router.use("/employeesetups", employeesetups({ config, db }));
  router.use("/initialstock", initialstock({ config, db }));
  router.use("/pharmacyGlobal", pharmacyGlobal({ config, db }));
  router.use("/posEntry", posEntry({ config, db }));
  router.use("/mrd", mrd({ config, db }));
  router.use("/requisitionEntry", requisitionEntry({ config, db }));
  router.use("/salesReturn", salesReturn({ config, db }));
  router.use("/transferEntry", transferEntry({ config, db }));
  router.use("/shiftAndCounter", shiftAndCounter({ config, db }));
  router.use("/ucaf", ucaf({ config, db }));
  router.use("/dcaf", dcaf({ config, db }));
  router.use("/ocaf", ocaf({ config, db }));
  router.use("/workBenchSetup", workBenchSetup({ config, db }));
  router.use("/invoiceGeneration", invoiceGeneration({ config, db }));
  router.use("/currency", currency({ config, db }));
  router.use("/generateReport", generateReport({ config, db }));
  router.use("/inventory", inventory({ config, db }));
  router.use("/inventoryinitialstock", inventoryinitialstock({ config, db }));
  router.use("/inventoryGlobal", inventoryGlobal({ config, db }));
  router.use(
    "/inventoryrequisitionEntry",
    inventoryrequisitionEntry({ config, db })
  );
  router.use("/inventorytransferEntry", inventorytransferEntry({ config, db }));
  router.use("/specialityAndCategory", specialityAndCategory({ config, db }));
  router.use("/vendor", vendor({ config, db }));
  router.use("/PurchaseOrderEntry", PurchaseOrderEntry({ config, db }));
  router.use("/DeliveryNoteEntry", DeliveryNoteEntry({ config, db }));
  router.use("/nurseWorkBench", nurseWorkBench({ config, db }));
  router.use("/ReceiptEntry", ReceiptEntry({ config, db }));
  router.use("/algaehMasters", algaehMasters({ config, db }));
  router.use("/opBillCancellation", opBillCancellation({ config, db }));
  router.use("/dental", dental({ config, db }));
  router.use("/opCreditSettlement", opCreditSettlement({ config, db }));
  router.use("/POSCreditSettlement", POSCreditSettlement({ config, db }));

  router.use("/selfService", selfService({ config, db }));
  router.use("/leave", leave({ config, db }));
  router.use("/holiday", holiday({ config, db }));
  router.use("/loan", loan({ config, db }));
  router.use("/salary", salary({ config, db }));
  router.use("/payrollSettings", payrollSettings({ config, db }));
  router.use("/algaehappexpiry", algaehappexpiry({ config, db }));
  router.use("/examinationDiagram", examinationDiagrams());
  router.use("/dentalForm", dentalForm({ config, db }));
  router.use("/opthometry", opthometry({ config, db }));
  router.use("/diagram", diagram({ config, db }));

//});

export default router;
