import express from "express";

import leave_approval from "../controllers/leave_approval";
import attendance from "../controllers/attandance";
import salary from "../controllers/salary";
import employee from "../controllers/employee";
import employee_payments from "../controllers/employee_payments";
import encashment_process from "../controllers/encashment_process";
import leave_salary_process from "../controllers/leave_salary_process";
import SelfService from "../controllers/selfService";
import test from "../controllers/test";
import end_of_service from "../controllers/end_of_service";
import final_settlement from "../controllers/final_settlement";
import payrollOptions from "../controllers/payrollOptions";
import OTManagement from "../controllers/OTManagement";
import leavesalaryaccural from "../controllers/leave_salary_accural";
import payrollsettings from "../controllers/payrollsettings";
import hrsettings from "../controllers/hrsettings";
import employeeDocuments from "../controllers/employee_documents";
import leave from "../controllers/leave";
import loan from "../controllers/loan";
import shift_roster from "../controllers/shift_roster";
import excelFile from "../controllers/excel_file";
import projectjobcosting from "../controllers/project_job_costing";
import openingBalanceUpload from "../controllers/openingBalanceUpload";
import salarypayment from "../controllers/salarypayment";

const router = express();
router.use("/attendance", attendance());
router.use("/employee", employee());
router.use("/leave", leave_approval());

router.use("/salary", salary());
router.use("/test", test());
router.use("/employeepayments", employee_payments());
router.use("/encashmentprocess", encashment_process());
router.use("/endofservice", end_of_service());
router.use("/finalsettlement", final_settlement());
router.use("/leavesalaryprocess", leave_salary_process());
router.use("/payrollOptions", payrollOptions());
router.use("/OTManagement", OTManagement());
router.use("/leavesalaryaccural", leavesalaryaccural());
router.use("/payrollsettings", payrollsettings());
router.use("/hrsettings", hrsettings());
router.use("/leave", leave());
router.use("/selfService", SelfService());
router.use("/loan", loan());
router.use("/documents", employeeDocuments());
router.use("/shift_roster", shift_roster());
router.use("/excel", excelFile());
router.use("/projectjobcosting", projectjobcosting());
router.use("/openingBalanceUpload", openingBalanceUpload());
router.use("/salarypayment", salarypayment());

export default router;
