import moment from "moment";

export default {
  inputParam: function() {
    var output;
    var CurrentDate = new Date();
    output = {
      hims_f_billing_header_id: null,
      patient_id: null,
      billing_type_id: null,
      visit_id: null,
      bill_number: null,
      incharge_or_provider: null,
      bill_date: moment(CurrentDate),
      advance_amount: 0,
      discount_amount: 0,
      sub_total_amount: 0,
      total_tax: 0,
      net_total: 0,
      advance_adjust: 0,
      billing_status: null,
      copay_amount: 0,
      deductable_amount: 0,
      gross_total: 0,
      sheet_discount_amount: 0,
      sheet_discount_percentage: 0,
      net_amount: 0,
      patient_res: 0,
      company_res: 0,
      sec_company_res: 0,
      patient_payable: 0,
      company_payable: 0,
      sec_company_payable: 0,
      patient_tax: 0,
      company_tax: 0,
      sec_company_tax: 0,
      net_tax: 0,
      credit_amount: 0,
      receiveable_amount: 0,
      created_by: null,
      created_date: null,
      updated_by: null,
      updated_date: null,
      record_status: null,
      cancel_remarks: null,
      cancel_by: null,
      bill_comments: null,
      details: [
        {
          hims_f_billing_details_id: null,
          hims_f_billing_header_id: null,
          service_type_id: null,
          services_id: null,
          quantity: 0,
          unit_cost: 0,
          gross_amount: 0,
          discount_amout: 0,
          discount_percentage: 0,
          net_amout: 0,
          copay_percentage: 0,
          copay_amount: 0,
          deductable_amount: 0,
          deductable_percentage: 0,
          tax_inclusive: "N",
          patient_tax: 0,
          company_tax: 0,
          total_tax: 0,
          patient_resp: 0,
          patient_payable: 0,
          comapany_resp: 0,
          company_payble: 0,
          sec_company: 0,
          sec_deductable_percentage: 0,
          sec_deductable_amount: 0,
          sec_company_res: 0,
          sec_company_tax: 0,
          sec_company_paybale: 0,
          sec_copay_percntage: 0,
          sec_copay_amount: 0,
          created_by: null,
          created_date: null,
          updated_by: null,
          updated_date: null
        }
      ]
    };
    return output;
  }
};
