export default {
  inputParam: function(param) {
    var output;

    output = {
      hims_d_employee_id: null,
      employee_code: null,
      services_id: null,
      title_id: null,
      first_name: null,
      middle_name: null,
      last_name: null,
      full_name: null,
      arabic_name: null,
      employee_designation_id: null,
      license_number: null,
      sex: null,
      date_of_birth: null,
      date_of_joining: null,
      date_of_resignation: null,
      category_id: null,
      speciality_id: null,
      employee_id: null,
      address: null,
      address2: null,
      pincode: null,
      city_id: null,
      state_id: null,
      country_id: null,
      Applicable: false,
      same_address: false,
      primary_contact_no: null,
      secondary_contact_number: null,
      email: null,
      emergancy_contact_person: null,
      emergancy_contact_no: 0,
      blood_group: null,
      sub_department_id: null,
      religion_id: null,
      overtime_group_id: null,

      appointment_type: null,
      employee_type: null,
      employee_bank_name: null,
      employee_bank_ifsc_code: null,
      employee_account_number: null,
      employee_bank_id: null,
      company_bank_id: null,
      mode_of_payment: null,
      inactive_date: null,
      employee_group_id: null,

      isdoctor: "N",
      employee_status: "A",

      servTypeCommission: [],
      serviceComm: [],

      deptDetails: [],
      dataPayrolExists: false,
      dataFamIdsExists: false,

      idDetails: [],
      dependentDetails: [],

      insertearnComp: [],
      insertDeductionComp: [],
      insertContributeComp: [],
      insertDependentDetails: [],
      insertdeptDetails: [],
      insertIdDetails: [],
      insertserviceComm: [],
      insertservTypeCommission: [],

      updateearnComp: [],
      updateDeductionComp: [],
      updateContributeComp: [],
      updateDependentDetails: [],
      updatedeptDetails: [],
      updateIdDetails: [],
      updateserviceComm: [],
      updateservTypeCommission: [],

      deleteearnComp: [],
      deleteDeductionComp: [],
      deleteContributeComp: [],
      deleteIdDetails: [],
      deleteDependentDetails: [],

      leave_salary_process: "N",
      late_coming_rule: "N",
      airfare_process: "N",
      exclude_machine_data: "N",
      gratuity_applicable: "N",
      suspend_salary: "N",

      selectedLang: "en",
      present_country_id: null,
      present_state_id: null,
      present_city_id: null,
      department_name: null,
      employeeImage: undefined,
      reporting_to_id: null
    };
    return output;
  }
};
