export default {
  inputParam: function (param) {
    var output;

    output = {
      hims_f_pharmacy_pos_header_id: null,
      pos_number: null,
      patient_id: null,
      patient_code: null,
      full_name: "",
      visit_id: null,
      visit_code: null,
      ip_id: null,
      pos_date: new Date(),
      recieve_amount: 0,
      year: null,
      period: null,
      location_id: 1,
      location_type: null,
      sub_total: 0,
      discount_percentage: 0,
      discount_amount: 0,
      net_total: 0,
      copay_amount: 0,
      patient_responsibility: 0,
      pos_customer_type: "OP",

      patient_name: null,
      referal_doctor: null,
      mobile_number: null,

      mode_of_pay: "",
      patient_tax: 0,
      patient_payable: 0,
      company_responsibility: 0,
      company_tax: 0,
      company_payable: 0,
      sec_company_responsibility: 0,
      sec_company_tax: 0,
      sec_company_payable: 0,
      sec_copay_amount: 0,
      net_tax: 0,
      gross_total: 0,
      advance_amount: 0,
      sheet_discount_amount: 0,
      sheet_discount_percentage: 0,
      net_amount: 0,
      credit_amount: 0,
      receiveable_amount: 0,
      posDetail: [],
      balance_credit: 0,
      //   selectedLang: "en",
      pharmacy_stock_detail: [],
      advance_adjust: 0,
      ItemUOM: [],
      qtyhand: 0,

      insured: "N",
      sec_insured: "N",
      insurance_yesno: "N",
      posted: "N",

      hims_f_receipt_header_id: null,
      receipt_number: null,
      receipt_date: new Date(),
      billing_header_id: null,
      total_amount: 0,
      counter_id: null,
      shift_id: null,
      unbalanced_amount: 0,
      receiptdetails: [],
      saveEnable: true,
      postEnable: true,
      episode_id: null,
      Cashchecked: true,
      Cardchecked: false,
      Checkchecked: false,
      pay_type: "R",

      card_number: null,
      effective_end_date: null,
      effective_start_date: null,
      insurance_provider_id: null,
      insurance_provider_name: null,
      sub_insurance_provider_id: null,
      sub_insurance_provider_name: null,
      network_id: null,
      network_type: null,
      policy_number: null,
      hims_d_insurance_network_office_id: null,

      secondary_card_number: null,
      secondary_effective_end_date: null,
      secondary_effective_start_date: null,
      secondary_insurance_provider_id: null,
      secondary_insurance_provider_name: null,
      secondary_network_id: null,
      secondary_network_type: null,
      secondary_policy_number: null,
      secondary_sub_insurance_provider_id: null,
      secondary_sub_insurance_provider_name: null,
      secondary_network_office_id: null,

      addItemButton: true,
      item_id: null,
      item_description: "",
      uom_id: null,
      batchno: null,
      expiry_date: null,
      quantity: 0,
      unit_cost: 0,
      Batch_Items: [],
      service_id: null,
      conversion_factor: 1,
      grn_no: null,
      item_group_id: null,
      item_category: null,
      dataExitst: false,
      vat_applicable: "Y",
      nationality_id: null,
      insert_pharmacy_stock: [],
      update_pharmacy_stock: [],
      delete_pharmacy_stock: [],
      posCancelled: false,
      InvoiceEnable: false,
      OTItemAddDis: false,
      patInsuranceFrontImg: undefined,
      patInsuranceBackImg: undefined,
      prescribed_item_list: [],
      prescribed_item: false
    };
    return output;
  }
};
