import { getCookie } from "../utils/algaehApiCall";

let prevLang = getCookie("Language");
export default {
  inputParam: function (param) {
    var output;
    const CurrentDate = new Date();
    output = {
      hims_d_patient_id: null,
      patient_code: "",
      registration_date: CurrentDate,
      title_id: null,
      first_name: "",
      middle_name: "",
      last_name: "",
      full_name: "",
      arabic_name: "",
      gender: null,
      religion_id: null,
      date_of_birth: null,
      hijiri_date: null,
      age: 0,
      marital_status: null,
      address1: "",
      address2: "",
      contact_number: null,
      secondary_contact_number: null,
      email: "",
      emergency_contact_name: "",
      emergency_contact_number: null,
      relationship_with_patient: "",
      visa_type_id: null,
      nationality_id: null,
      postal_code: "",
      country_id: null,
      state_id: null,
      city_id: null,
      primary_identity_id: null,
      primary_id_no: "",
      secondary_identity_id: null,
      secondary_id_no: "",
      photo_file: "",
      primary_id_file: "",
      secondary_id_file: "",

      hims_f_patient_appointment_id: null,

      visit_type: null,
      visit_date: CurrentDate,
      department_id: null,
      sub_department_id: null,
      doctor_id: null,
      maternity_patient: "N",
      is_mlc: "N",
      mlc_accident_reg_no: "",
      mlc_police_station: "",
      mlc_wound_certified_date: "",
      visit_code: "",
      visitDetails: [],
      patient_id: null,
      hims_d_services_id: null,
      patient_visit_id: null,
      consultation: null,
      appointment_patient: "N",
      doctor_name: null,
      service_name: null,

      provider_id: null,
      source: "O",
      status: "V",
      checked_in: "N",
      nurse_examine: "N",
      patient_type: null,
      patient_Image: null,
      filePreview: null,
      filePrimaryPreview: null,
      vat_applicable: "N",
      mode_of_pay: null,

      widthImg: "",
      open: false,
      vertical: null,
      horizontal: null,
      DialogOpen: false,
      sideBarOpen: false,
      sidBarOpen: true,
      selectedLang: prevLang,
      chnageLang: false,
      AGEMM: 0,
      AGEDD: 0,
      breadCrumbWidth: null,
      saveEnable: true,
      clearData: true,
      pay_cash: "CA",
      pay_card: "CD",
      pay_cheque: "CH",
      cash_amount: 0,
      card_number: "",
      card_date: null,
      card_amount: 0,
      cheque_number: "",
      cheque_date: null,
      cheque_amount: 0,
      advance: 0,
      existingPatient: false,
      savedData: false,
      insured: "N",
      sec_insured: "N",
      insuranceYes: true,
      sec_insuranceYes: true,
      age_in_years: null,
      age_in_months: null,
      age_in_days: null,
      payment_type: "S",
      card_numbr: "",
      new_visit_patient: "N",

      primary_insurance_provider_id: null,
      primary_sub_id: null,
      primary_network_id: null,
      primary_policy_num: null,
      primary_effective_start_date: null,
      primary_effective_end_date: null,
      primary_inc_card_path: null,
      primary_card_number: null,
      primary_network_office_id: null,

      secondary_insurance_provider_id: null,
      secondary_sub_id: null,
      secondary_network_id: null,
      secondary_effective_start_date: null,
      secondary_effective_end_date: null,
      secondary_policy_num: null,
      secondary_card_number: null,
      secondary_network_office_id: null,

      checked_existing_plan: false,
      checked_maternity_patient: false,

      radioNo: true,
      radioYes: false,
      radioSecNo: true,
      radioSecYes: false,
      hideInsurance: false,
      hideSecInsurance: false,
      existing_plan: "N",
      department_type: "N",
      treatment_plan_id: null,
      patientImage: undefined,
      patientIdCard: undefined,
      patInsuranceFrontImg: undefined,
      patInsuranceBackImg: undefined,
      patSecInsuranceFrontImg: undefined,
      patSecInsuranceBackImg: undefined,
      forceRefresh: undefined,
      Rerender: false,

      card_holder_name: null,
      card_holder_age: null,
      card_holder_gender: null,
      card_class: null,
      employee_id: null,
      popUpGenereted: false,
      advanceEnable: true,
      advance_amount: 0,
      from_package: false,
      package_details: [],
      utilize_amount: 0,
      balance_amount: 0,
      hims_f_package_header_id: null,
      follow_up: false,
      existing_treat: false,
      eligible: "N",
      checked_eligible: false,
      eligible_reference_number: null
    };
    return output;
  }
};
