export default {
  inputParam: function(param) {
    var output;

    output = {
      hims_f_pharmcy_sales_return_header_id: null,
      sales_return_number: null,
      pos_number: null,
      patient_id: null,
      patient_code: null,
      full_name: "",
      visit_id: null,
      visit_code: null,
      ip_id: null,
      from_pos_id: null,
      sales_return_date: new Date(),
      year: null,
      period: null,
      location_id: null,
      location_type: null,
      sub_total: 0,
      discount_percentage: 0,
      discount_amount: 0,
      net_total: 0,
      copay_amount: 0,
      patient_responsibility: 0,
      location_description: null,

      patient_tax: 0,
      patient_payable: 0,
      company_responsibility: 0,
      company_tax: 0,
      company_payable: 0,
      comments: null,
      sec_company_responsibility: 0,
      sec_company_tax: 0,
      sec_company_payable: 0,
      sec_copay_amount: 0,
      net_tax: 0,
      gross_total: 0,
      advance_amount: 0,
      sheet_discount_amount: 0,
      sheet_discount_percentage: 0,
      net_amount: 0,
      credit_amount: 0,
      payable_amount: 0,

      //   selectedLang: "en",
      pharmacy_stock_detail: [],
      advance_adjust: 0,
      ItemUOM: [],

      pos_customer_type: "OT",
      mode_of_pay: "1",
      dataChange: false,
      insured: "N",
      sec_insured: "N",

      hims_f_receipt_header_id: null,
      receipt_number: null,
      receipt_date: new Date(),
      billing_header_id: null,
      total_amount: 0,
      counter_id: null,
      shift_id: null,
      unbalanced_amount: 0,
      receiptdetails: [],
      saveEnable: true,
      postEnable: true,
      episode_id: null,
      Cashchecked: true,
      Cardchecked: false,
      Checkchecked: false,
      pay_type: "P",

      card_number: null,
      effective_end_date: null,
      effective_start_date: null,
      insurance_provider_id: null,
      insurance_provider_name: null,
      sub_insurance_provider_id: null,
      sub_insurance_provider_name: null,
      network_id: null,
      network_type: null,
      policy_number: null,
      hims_d_insurance_network_office_id: null,

      secondary_card_number: null,
      secondary_effective_end_date: null,
      secondary_effective_start_date: null,
      secondary_insurance_provider_id: null,
      secondary_insurance_provider_name: null,
      secondary_network_id: null,
      secondary_network_type: null,
      secondary_policy_number: null,
      secondary_sub_insurance_provider_id: null,
      secondary_sub_insurance_provider_name: null,
      secondary_network_office_id: null,

      item_id: null,
      uom_id: null,
      batchno: null,
      expiry_date: null,
      quantity: 0,
      unit_cost: 0,
      Batch_Items: [],
      service_id: null,
      conversion_factor: 1,
      grn_no: null,
      item_group_id: null,
      vat_applicable: "Y"
    };
    return output;
  }
};
